import { NextRequest, NextResponse } from "next/server";
import cloudinary, { UploadApiResponse } from "cloudinary";
import connectDB from "@/lib/mongodb";
import { Event } from "@/database";

/**
 * GET /api/events
 * Fetch all events or filter by query parameters
 */
export async function GET(request: NextRequest) {
  try {
    await connectDB();

    const { searchParams } = new URL(request.url);
    const mode = searchParams.get("mode");
    const tag = searchParams.get("tag");

    // Build query filter
    const filter: Record<string, unknown> = {};
    if (mode) filter.mode = mode;
    if (tag) filter.tags = { $in: [tag] };

    const events = await Event.find(filter).sort({ date: 1, time: 1 });

    return NextResponse.json({
      success: true,
      count: events.length,
      data: events,
    });
  } catch (error) {
    console.error("Error fetching events:", error);
    return NextResponse.json(
      {
        success: false,
        error: "Failed to fetch events",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}

/**
 * POST /api/events
 * Create a new event
 */
export async function POST(request: NextRequest) {
  try {
    await connectDB();

    const formData = await request.formData();

    // Extract and validate event data
    const eventData = {
      title: formData.get("title") as string,
      description: formData.get("description") as string,
      overview: formData.get("overview") as string,
      image: "",
      venue: formData.get("venue") as string,
      location: formData.get("location") as string,
      date: formData.get("date") as string,
      time: formData.get("time") as string,
      mode: formData.get("mode") as string,
      audience: formData.get("audience") as string,
      organizer: formData.get("organizer") as string,
      agenda: JSON.parse(formData.get("agenda") as string),
      tags: JSON.parse(formData.get("tags") as string),
    };

    const file = formData.get("image") as File;
    if(!file){
        return NextResponse.json(
            {
                success: false,
                error: "Image is required",
            },
            { status: 400 }
        );
    }

    const arrayBuffer = await file.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    const uploadResult = await new Promise<UploadApiResponse>((resolve, reject) => { // this will contain the URL of the image.
        cloudinary.v2.uploader.upload_stream(
            {
                resource_type: "image",
                folder: "event-images",
            },
            (error, result) => {
                if (error) {
                    reject(error);
                } else if (result) {
                    resolve(result);
                } else {
                    reject(new Error("Upload failed"));
                }
            }
        ).end(buffer);
    });

    eventData.image = (uploadResult as {secure_url: string}).secure_url;

    // Create event (slug will be auto-generated by pre-save hook)
    const event = await Event.create(eventData);

    return NextResponse.json(
      {
        success: true,
        message: "Event created successfully",
        data: event,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error("Error creating event:", error);

    // Handle validation errors
    if (error instanceof Error && error.name === "ValidationError") {
      return NextResponse.json(
        {
          success: false,
          error: "Validation failed",
          message: error.message,
        },
        { status: 400 }
      );
    }

    // Handle duplicate slug error
    if (error instanceof Error && "code" in error && error.code === 11000) {
      return NextResponse.json(
        {
          success: false,
          error: "Event with similar title already exists",
        },
        { status: 409 }
      );
    }

    return NextResponse.json(
      {
        success: false,
        error: "Event creation failed",
        message: error instanceof Error ? error.message : "Unknown error",
      },
      { status: 500 }
    );
  }
}
